# Generated by Django 3.0.8 on 2020-09-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0047_culture_event_culture_genre_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('session_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
