# Generated by Django 3.0.8 on 2020-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0048_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weather',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
    ]
