# Generated by Django 3.0.8 on 2020-09-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0049_auto_20200908_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session_id',
            new_name='id',
        ),
    ]
